name: Build

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build App
      run: xcodebuild -project LaunchNext.xcodeproj -scheme LaunchNext -configuration Release ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO clean build

    - name: Package .app
      run: |
        mkdir -p output
        APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "LaunchNext.app" | head -n 1)
        echo "$APP_PATH"
        cp -R "$APP_PATH" output/LaunchNext.app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LaunchNext
        path: output
